name: run Unity project

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run executable file
        run: |
          cd Build
          ./SFMServer.exe
      - name: Keep SFMServer running
        run: |
          while true
          do
            sleep 60
            ps aux | grep SFMServer.exe | grep -v grep || ./Build/SFMServer.exe &
          done
